GSoC2011SfM: OpencvSfM::EuclideanEstimator Class Reference
OpencvSfM::EuclideanEstimator Class Reference
This class perform a projective estimation of the motion. Given points matches and cameras with intra parameters, it tries to find the best cameras positions and 3D points. Does not perform a bundle ajustement!
#include <EuclideanEstimator.h>
Public Member Functions
EuclideanEstimator (SequenceAnalyzer &sequence, std::vector< PointOfView > &cameras)
virtual ~EuclideanEstimator (void)
void addNewPointOfView (const PointOfView &camera)
void computeReconstruction ()
void bundleAdjustement ()
void viewEstimation ()
void initialReconstruction (int image1, int image2)
bool cameraResection (unsigned int image)
Public Attributes
std::vector< TrackOfPoints > point_computed_
list of 3D points computed
std::vector< bool > camera_computed_
List of camera computed.
Protected Attributes
int index_origin
index of camera set as origin...
libmv::vector< libmv::Mat3 > intra_params_
Intra parameters of cameras (don't use them, they are strongly related to cameras_ attribut!
libmv::vector< libmv::Mat3 > rotations_
rotations matrix of cameras (don't use them, they are strongly related to cameras_ attribut!
libmv::vector< libmv::Vec3 > translations_
translation vectors of cameras (don't use them, they are strongly related to cameras_ attribut!
std::vector< PointOfView > & cameras_
List of cameras (intra and extern parameters...)
SequenceAnalyzer & sequence_
Object containing all 2D information of this sequence.
Detailed Description
This class perform a projective estimation of the motion. Given points matches and cameras with intra parameters, it tries to find the best cameras positions and 3D points. Does not perform a bundle ajustement!
As this class use a lot of libmv functions, the data members are using libmv structures...
Definition at line 23 of file EuclideanEstimator.h.
Constructor & Destructor Documentation
OpencvSfM::EuclideanEstimator::EuclideanEstimator (SequenceAnalyzer & sequence, std::vector< PointOfView > & cameras)
Construct an euclidean estimator using a sequence of 2D points matches and a list of camera guess (intra parameters should be known!)
Parameters:
sequence Object containing all 2D information of this sequence
cameras List of cameras (intra (and extern if available) parameters...)
Definition at line 114 of file EuclideanEstimator.cpp.
OpencvSfM::EuclideanEstimator::~EuclideanEstimator (void) [virtual]
Destructor of EuclideanEstimator
Definition at line 127 of file EuclideanEstimator.cpp.
Member Function Documentation
void OpencvSfM::EuclideanEstimator::addNewPointOfView (const PointOfView & camera)
Add a new camera to the estimator
Parameters:
camera new point of view to add for reconstruction
Definition at line 132 of file EuclideanEstimator.cpp.
Referenced by EuclideanEstimator().
void OpencvSfM::EuclideanEstimator::bundleAdjustement ()
Run a bundle adjustment using every computed cameras and every computed 3D points
Definition at line 148 of file EuclideanEstimator.cpp.
Referenced by computeReconstruction().
bool OpencvSfM::EuclideanEstimator::cameraResection (unsigned int image)
Find the position of a new camera
Parameters:
image index of the wanted camera
Definition at line 452 of file EuclideanEstimator.cpp.
Referenced by computeReconstruction().
void OpencvSfM::EuclideanEstimator::computeReconstruction ()
comptue cameras and structure if intra parameters are known.
Definition at line 744 of file EuclideanEstimator.cpp.
void OpencvSfM::EuclideanEstimator::initialReconstruction (int image1, int image2)
Create a new Euclidean reconstruction using matches between two images
Parameters:
image1 index of the first image
image2 index of the second image
Definition at line 652 of file EuclideanEstimator.cpp.
Referenced by computeReconstruction().
void OpencvSfM::EuclideanEstimator::viewEstimation ()
Show this estimation
Definition at line 868 of file EuclideanEstimator.cpp.
Referenced by computeReconstruction().
The documentation for this class was generated from the following files:
D:/Travail/These/Determination caracteristiques camera/GSoC/SfM/src/EuclideanEstimator.h
D:/Travail/These/Determination caracteristiques camera/GSoC/SfM/src/EuclideanEstimator.cpp