#ifndef LIBMV_REVISION_H_
#define LIBMV_REVISION_H_

#define LIBMV_VERSION_MAJOR 0
#define LIBMV_VERSION_MINOR 1
#define LIBMV_VERSION_PATCH 0
#define LIBMV_VERSION "0.1.0"

#endif //LIBMV_REVISION_H_
