GSoC2011SfM: OpencvSfM::StructureEstimator Class Reference
OpencvSfM::StructureEstimator Class Reference
This class tries to find the 3D structure using a sequence and cameras fully parameterized.
#include <StructureEstimator.h>
Public Member Functions
StructureEstimator (SequenceAnalyzer *sequence, std::vector< PointOfView > *cameras, int max_repro_error=10)
~StructureEstimator ()
std::vector< char > computeStructure (unsigned int max_error=10)
std::vector< TrackOfPoints > computeStructure (const std::vector< int > &list_of_images, unsigned int max_error=10)
void removeOutliersTracks (double max_error=10, std::vector< TrackOfPoints > *list_of_tracks=NULL)
Protected Attributes
SequenceAnalyzer * sequence_
Object containing all 2D information of this sequence.
std::vector< PointOfView > * cameras_
List of cameras (intra and extern parameters...)
int max_repro_error_
Maximum reprojection error allowed.
Detailed Description
This class tries to find the 3D structure using a sequence and cameras fully parameterized.
Definition at line 16 of file StructureEstimator.h.
Constructor & Destructor Documentation
OpencvSfM::StructureEstimator::StructureEstimator (SequenceAnalyzer * sequence, std::vector< PointOfView > * cameras, int max_repro_error = 10) [inline]
Constructor of this 3D structure estimator
Parameters:
sequence the address of the object containing all 2D information of this sequence
cameras List of cameras (intra and extern parameters...)
max_repro_error Maximum reprojection error allowed
Definition at line 30 of file StructureEstimator.h.
OpencvSfM::StructureEstimator::~StructureEstimator () [inline]
Destructor will not release datas as they where given by address!
Definition at line 38 of file StructureEstimator.h.
Member Function Documentation
vector< char > OpencvSfM::StructureEstimator::computeStructure (unsigned int max_error = 10)
Project previously 2D points matches using cameras parameters
Parameters:
max_error maximum error allowed.
Returns:
the mask of correct points (0 if error > max_error)
Definition at line 12 of file StructureEstimator.cpp.
Referenced by OpencvSfM::EuclideanEstimator::computeReconstruction(), and OpencvSfM::EuclideanEstimator::initialReconstruction().
std::vector< TrackOfPoints > OpencvSfM::StructureEstimator::computeStructure (const std::vector< int > & list_of_images, unsigned int max_error = 10)
Project previously 2D points matches for only two views
Parameters:
list_of_images list of image indexes to use
max_error maximum error allowed.
Returns:
output of tracks triangulated (contain 3D point)
Definition at line 46 of file StructureEstimator.cpp.
void OpencvSfM::StructureEstimator::removeOutliersTracks (double max_error = 10, std::vector< TrackOfPoints > * list_of_tracks = NULL)
Remove points from track when projection error > max_error
Parameters:
max_error maximum error of back projection allowed
list_of_tracks list of tracks to work with. If NULL or not set, will use StructureEstimator::sequence_
Definition at line 95 of file StructureEstimator.cpp.
Referenced by OpencvSfM::EuclideanEstimator::computeReconstruction().
The documentation for this class was generated from the following files:
D:/Travail/These/Determination caracteristiques camera/GSoC/SfM/src/StructureEstimator.h
D:/Travail/These/Determination caracteristiques camera/GSoC/SfM/src/StructureEstimator.cpp