GSoC2011SfM: OpencvSfM::PointsToTrack Class Reference
OpencvSfM::PointsToTrack Class Reference
This class can be used to store informations about point and features. This is an abstract class: you can't use it directly. Use for instance PointsToTrackWithImage.
#include <PointsToTrack.h>
Public Member Functions
PointsToTrack (int corresponding_image=-1, std::vector< cv::KeyPoint > keypoints=std::vector< cv::KeyPoint >(0), cv::Mat descriptors=cv::Mat())
virtual ~PointsToTrack (void)
virtual int computeKeypointsAndDesc (bool forcing_recalculation=false)
virtual int computeKeypoints ()
virtual void computeDescriptors ()
void addKeypoints (std::vector< cv::KeyPoint > keypoints, cv::Mat descriptors=cv::Mat(), bool computeMissingDescriptor=false)
unsigned int addKeypoint (cv::KeyPoint point)
const std::vector< cv::KeyPoint > & getKeypoints () const
void getKeyMatches (const std::vector< TrackOfPoints > &matches, int otherImage, std::vector< cv::Point2f > &pointsVals) const
const cv::KeyPoint & getKeypoint (unsigned int index) const
cv::Mat getDescriptors () const
void printPointsOnImage (const cv::Mat &image, cv::Mat &outImg, const cv::Scalar &color=cv::Scalar::all(-1), int flags=cv::DrawMatchesFlags::DEFAULT) const
Static Public Member Functions
static void read (const cv::FileNode &node, PointsToTrack &points)
static void write (cv::FileStorage &fs, const PointsToTrack &points)
Protected Attributes
std::vector< cv::KeyPoint > keypoints_
This attribute will store points coordinates and sometimes orientation and size.
cv::Mat descriptors_
this attribute will store descritors for each points in a matrix with size (n*m), where n is the number of points and m is the desciptor size.
int corresponding_image_
index of frame when available
Static Protected Attributes
static int glob_number_images_ = 0
total numbers of images!
Detailed Description
This class can be used to store informations about point and features. This is an abstract class: you can't use it directly. Use for instance PointsToTrackWithImage.
To create a structure from motion, most methods use points to compute the structure. This class focus on the first task in SfM: find points in image which are easy to track... When available, a feature vector for each points is very helpful: the matching will be easier.
Definition at line 24 of file PointsToTrack.h.
Constructor & Destructor Documentation
OpencvSfM::PointsToTrack::PointsToTrack (int corresponding_image = -1, std::vector< cv::KeyPoint > keypoints = std::vector<cv::KeyPoint>(0), cv::Mat descriptors = cv::Mat())
this constructor create an object with available information...
Parameters:
corresponding_image Global index of image
keypoints the points we will try to track...
descriptors the feature vector for each points...
Definition at line 14 of file PointsToTrack.cpp.
OpencvSfM::PointsToTrack::~PointsToTrack (void) [virtual]
Destructor : delete points and features vectors
Definition at line 27 of file PointsToTrack.cpp.
Member Function Documentation
unsigned int OpencvSfM::PointsToTrack::addKeypoint (cv::KeyPoint point) [inline]
This method is used to add a keypoint at the end of the points vector...
Parameters:
keypoints Keypoints to add
Returns:
index of the keypoint.
Definition at line 73 of file PointsToTrack.h.
void OpencvSfM::PointsToTrack::addKeypoints (std::vector< cv::KeyPoint > keypoints, cv::Mat descriptors = cv::Mat(), bool computeMissingDescriptor = false)
This method is used to add Keypoints...
Parameters:
keypoints Keypoints to add
descriptors of points, if any
computeMissingDescriptor if true, the missing descriptors are computed.
Definition at line 67 of file PointsToTrack.cpp.
void OpencvSfM::PointsToTrack::computeDescriptors () [virtual]
This method is used to compute only descriptors...
Reimplemented in OpencvSfM::PointsToTrackWithImage.
Definition at line 63 of file PointsToTrack.cpp.
Referenced by addKeypoints(), and computeKeypointsAndDesc().
int OpencvSfM::PointsToTrack::computeKeypoints () [virtual]
This method is used to compute only Keypoints...
Returns:
the number of points
Reimplemented in OpencvSfM::PointsToTrackWithImage.
Definition at line 57 of file PointsToTrack.cpp.
Referenced by computeKeypointsAndDesc().
int OpencvSfM::PointsToTrack::computeKeypointsAndDesc (bool forcing_recalculation = false) [virtual]
This method is used to compute both Keypoints and descriptors...
Parameters:
forcing_recalculation if true previous keypoints are removed... If false and if keypoints and descriptor exists, nothing is done.
Returns:
the number of points
Definition at line 34 of file PointsToTrack.cpp.
cv::Mat OpencvSfM::PointsToTrack::getDescriptors () const [inline]
this method return the descritors for each points in a matrix with size (n*m), where n is the number of points and m is the desciptor size.
Returns:
descritors for each points in a matrix with size (n*m), where n is the number of points and m is the desciptor size.
Definition at line 98 of file PointsToTrack.h.
void OpencvSfM::PointsToTrack::getKeyMatches (const std::vector< TrackOfPoints > & matches, int otherImage, std::vector< cv::Point2f > & pointsVals) const
this method return the points coordinates corresponding to tracks
Parameters:
matches list of tracks. Only points found in tracks are returned
pointsVals [out] points found in tracks
Definition at line 136 of file PointsToTrack.cpp.
const cv::KeyPoint& OpencvSfM::PointsToTrack::getKeypoint (unsigned int index) const [inline]
this method return the points coordinates of the i^th entry
Parameters:
index number of keypoints wanted
Returns:
points coordinates and when available orientation and size
Definition at line 92 of file PointsToTrack.h.
const std::vector<cv::KeyPoint>& OpencvSfM::PointsToTrack::getKeypoints () const [inline]
this method return the points coordinates and sometimes orientation and size
Returns:
points coordinates and when available orientation and size
Definition at line 79 of file PointsToTrack.h.
void OpencvSfM::PointsToTrack::printPointsOnImage (const cv::Mat & image, cv::Mat & outImg, const cv::Scalar & color = cv::Scalar::all(-1), int flags = cv::DrawMatchesFlags::DEFAULT) const
To show the points on image, use this function to draw points on it.
Parameters:
image Source image.
outImg Output image. Its content depends on flags value what is drawn in output image. See possible flags bit values.
color Color of keypoints
flags Possible flags bit values is defined by DrawMatchesFlags (see http://opencv.willowgarage.com/documentation/cpp/features2d_drawing_function_of_keypoints_and_matches.html#cv-drawmatches)
Definition at line 97 of file PointsToTrack.cpp.
The documentation for this class was generated from the following files:
D:/Travail/These/Determination caracteristiques camera/GSoC/SfM/src/PointsToTrack.h
D:/Travail/These/Determination caracteristiques camera/GSoC/SfM/src/PointsToTrack.cpp